export const INTEL_GPU_PCI_ID_MAP: Record<string, string> = {
  '4541': 'Intel® UHD Graphics [Elkhart Lake]',
  '4551': 'Intel® UHD Graphics [Elkhart Lake]',
  '4555': 'Intel® UHD Graphics [Elkhart Lake]',
  '4557': 'Intel® UHD Graphics [Elkhart Lake]',
  '4571': 'Intel® UHD Graphics [Elkhart Lake]',
  '4626': 'Intel® UHD Graphics [Alder Lake-P]',
  '4628': 'Intel® UHD Graphics [Alder Lake-P]',
  '4680': 'Intel® UHD Graphics 770 [Alder Lake-S]',
  '4682': 'Intel® UHD Graphics 730 [Alder Lake-S]',
  '4688': 'Intel® UHD Graphics 770 [Alder Lake-S]',
  '4690': 'Intel® UHD Graphics 770 [Alder Lake-S]',
  '4692': 'Intel® UHD Graphics 730 [Alder Lake-S]',
  '4693': 'Intel® UHD Graphics 710 [Alder Lake-S]',
  '4905': 'Intel® Iris® Xe MAX Graphics [DG1]',
  '4907': 'Intel Server GPU SG-18M [DG1]',
  '4908': 'Intel® Iris® Xe Graphics [DG1]',
  '4909': 'Intel® Iris® Xe MAX 100 Graphics [DG1]',
  '5690': 'Intel® Arc™ A770M Graphics [Alchemist]',
  '5691': 'Intel® Arc™ A730M Graphics [Alchemist]',
  '5692': 'Intel® Arc™ A550M Graphics [Alchemist]',
  '5693': 'Intel® Arc™ A370M Graphics [Alchemist]',
  '5694': 'Intel® Arc™ A350M Graphics [Alchemist]',
  '5696': 'Intel® Arc™ A570M Graphics [Alchemist]',
  '5697': 'Intel® Arc™ A530M Graphics [Alchemist]',
  '6420': 'Intel® Graphics [Lunar Lake]',
  E20B: 'Intel® Arc™ B580 Graphics [Battlemage]',
  E20C: 'Intel® Arc™ B570 Graphics [Battlemage]',
  '64A0': 'Intel® Arc™ Graphics [Lunar Lake]',
  '64B0': 'Intel® Graphics [Lunar Lake]',
  '7D51': 'Intel® Graphics [Arrow Lake-H]',
  '7D67': 'Intel® Graphics [Arrow Lake-S]',
  '7D41': 'Intel® Graphics [Arrow Lake-U]',
  '7DD5': 'Intel® Graphics [Meteor Lake]',
  '7D45': 'Intel® Graphics [Meteor Lake]',
  '7D40': 'Intel® Graphics [Meteor Lake]',
  '7D55': 'Intel® Arc™ Graphics [Meteor Lake]',
  '0BD5': 'Intel® Data Center GPU Max 1550 [Ponte Vecchio]',
  '0BDA': 'Intel® Data Center GPU Max 1100 [Ponte Vecchio]',
  '56C0': 'Intel® Data Center GPU Flex 170 [Alchemist]',
  '56C1': 'Intel® Data Center GPU Flex 140 [Alchemist]',
  '56A0': 'Intel® Arc™ A770 Graphics [Alchemist]',
  '56A1': 'Intel® Arc™ A750 Graphics [Alchemist]',
  '56A2': 'Intel® Arc ™ A580 Graphics [Alchemist]',
  '56A5': 'Intel® Arc™ A380 Graphics [Alchemist]',
  '56A6': 'Intel® Arc™ A310 Graphics [Alchemist]',
  '56B3': 'Intel® Arc ™ Pro A60 Graphics [Alchemist]',
  '56B2': 'Intel® Arc ™ Pro A60M Graphics [Alchemist]',
  '56B1': 'Intel® Arc™ Pro A40/A50 Graphics [Alchemist]',
  '56B0': 'Intel® Arc™ Pro A30M Graphics [Alchemist]',
  '56BA': 'Intel® Arc™ A380E Graphics [Alchemist]',
  '56BC': 'Intel® Arc™ A370E Graphics [Alchemist]',
  '56BD': 'Intel® Arc™ A350E Graphics [Alchemist]',
  '56BB': 'Intel® Arc™ A310E Graphics [Alchemist]',
  A780: 'Intel® UHD Graphics 770 [Raptor Lake-S]',
  A781: 'Intel® UHD Graphics [Raptor Lake-S]',
  A788: 'Intel® UHD Graphics [Raptor Lake-S]',
  A789: 'Intel® UHD Graphics [Raptor Lake-S]',
  A78A: 'Intel® UHD Graphics [Raptor Lake-S]',
  A782: 'Intel® UHD Graphics 730 [Raptor Lake-S]',
  A78B: 'Intel® UHD Graphics [Raptor Lake-S]',
  A783: 'Intel® UHD Graphics 710 [Raptor Lake-S]',
  A7A0: 'Intel® Iris® Xe Graphics [Raptor Lake-P]',
  A7A1: 'Intel® Iris® Xe Graphics [Raptor Lake-P]',
  A7A8: 'Intel® UHD Graphics [Raptor Lake-P]',
  A7AA: 'Intel® Graphics [Raptor Lake-P]',
  A7AB: 'Intel® Graphics [Raptor Lake-P]',
  A7AC: 'Intel® Graphics [Raptor Lake-U]',
  A7AD: 'Intel® Graphics [Raptor Lake-U]',
  A7A9: 'Intel® UHD Graphics [Raptor Lake-P]',
  A721: 'Intel® UHD Graphics [Raptor Lake-P]',
  '468A': 'Intel® UHD Graphics 770 [Alder Lake-S]',
  '468B': 'Intel® UHD Graphics 770 [Alder Lake-S]',
  '46D3': 'Intel® Graphics [Alder Lake-N]',
  '46D4': 'Intel® Graphics [Alder Lake-N]',
  '46D0': 'Intel® UHD Graphics [Alder Lake-N]',
  '46D1': 'Intel® UHD Graphics [Alder Lake-N]',
  '46D2': 'Intel® UHD Graphics [Alder Lake-N]',
  '462A': 'Intel® UHD Graphics [Alder Lake-P]',
  '46A2': 'Intel® UHD Graphics [Alder Lake-P]',
  '46B3': 'Intel® UHD Graphics [Alder Lake-P]',
  '46C2': 'Intel® UHD Graphics [Alder Lake-P]',
  '46A3': 'Intel® UHD Graphics [Alder Lake-P]',
  '46B2': 'Intel® UHD Graphics [Alder Lake-P]',
  '46C3': 'Intel® UHD Graphics [Alder Lake-P]',
  '46A0': 'Intel® Iris® Xe Graphics [Alder Lake-P]',
  '46B0': 'Intel® Iris® Xe Graphics [Alder Lake-P]',
  '46C0': 'Intel® Iris® Xe Graphics [Alder Lake-P]',
  '46A6': 'Intel® Iris® Xe Graphics [Alder Lake-P]',
  '46AA': 'Intel® Iris® Xe Graphics [Alder Lake-P]',
  '46A8': 'Intel® Iris® Xe Graphics [Alder Lake-P]',
  '46A1': 'Intel® Iris® Xe Graphics [Alder Lake-P]',
  '46B1': 'Intel® Iris® Xe Graphics [Alder Lake-P]',
  '46C1': 'Intel® Iris® Xe Graphics [Alder Lake-P]',
  '4C8A': 'Intel® UHD Graphics 750 [Rocket Lake]',
  '4C8B': 'Intel® UHD Graphics 730 [Rocket Lake]',
  '4C90': 'Intel® UHD Graphics P750 [Rocket Lake]',
  '4C9A': 'Intel® UHD Graphics P750 [Rocket Lake]',
  '4E71': 'Intel® UHD Graphics [Jasper Lake]',
  '4E61': 'Intel® UHD Graphics [Jasper Lake]',
  '4E57': 'Intel® UHD Graphics [Jasper Lake]',
  '4E55': 'Intel® UHD Graphics [Jasper Lake]',
  '4E51': 'Intel® UHD Graphics [Jasper Lake]',
  '9A59': 'Intel® UHD Graphics [Tiger Lake]',
  '9A78': 'Intel® UHD Graphics [Tiger Lake]',
  '9A60': 'Intel® UHD Graphics [Tiger Lake]',
  '9A70': 'Intel® UHD Graphics [Tiger Lake]',
  '9A68': 'Intel® UHD Graphics [Tiger Lake]',
  '9A40': 'Intel® Iris® Xe Graphics [Tiger Lake]',
  '9A49': 'Intel® Iris® Xe Graphics [Tiger Lake]',
}
